services:
  web:
    build: .
    container_name: knhow-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=4000
      - NODE_ENV=development
    stdin_open: true
    tty: true 